# 한전조수 가공 요금표 DB 업데이트 작업
* 주의사항 : 각 폴더에 있는 압축파일은 해당 폴더에 압축 해제해야한다.
* 월별 설정은 201901, 201902 포맷을 정해야한다.
* 파일명이 바뀔때는 오류가 발생할수 있음으로 세심하게 관리해야한다.

In [1]:
import os
import pandas as pd
import sqlite3

In [2]:
print('가공할 데이터의 년월을 입력해주세요. (예제 : 201901)')
month = input()

가공할 데이터의 년월을 입력해주세요. (예제 : 201901)
201905

In [3]:
## Path 설정
강원path = 'd:/Dev/한전조수분석/data/'+month+'/강원본부/'
경기path = 'd:/Dev/한전조수분석/data/'+month+'/경기본부/'
경기북부path = 'd:/Dev/한전조수분석/data/'+month+'/경기북부본부/'
경남path = 'd:/Dev/한전조수분석/data/'+month+'/경남본부/'
경북path = 'd:/Dev/한전조수분석/data/'+month+'/경북본부/'
남서울path = 'd:/Dev/한전조수분석/data/'+month+'/남서울본부/'
부산path = 'd:/Dev/한전조수분석/data/'+month+'/부산본부/'
서울path = 'd:/Dev/한전조수분석/data/'+month+'/서울본부/'
인천path = 'd:/Dev/한전조수분석/data/'+month+'/인천본부/'
전남path = 'd:/Dev/한전조수분석/data/'+month+'/전남본부/'
전북path = 'd:/Dev/한전조수분석/data/'+month+'/전북본부/조수별 공가요금 세부내역 조회/'
제주path = 'd:/Dev/한전조수분석/data/'+month+'/제주본부/'
충남path = 'd:/Dev/한전조수분석/data/'+month+'/충남본부/ST000가공/'
충북path = 'd:/Dev/한전조수분석/data/'+month+'/충북본부/'

## 전남 Path는 불필요한 파일이 많아서 별도의 Logic이 필요함 (조수별이 등록된 파일만 읽어오기)
def 조수별데이터불러오기(path) : 
    대상 = os.listdir(path)
    search = '조수별'
    for i in range(0,len(대상)):
        if search in 대상[i]:
            df = pd.read_excel(path+대상[i], encoding = 'euc-kr')
        else :
            pass
    return df

def 강원데이터불러오기(path) : 
    대상 = os.listdir(path)
    search = '가공'
    for i in range(0,len(대상)):
        if search in 대상[i]:
            df = pd.read_excel(path+대상[i], encoding = 'euc-kr')
        else :
            pass
    return df

def 경기북부데이터불러오기1(path) : 
    대상 = os.listdir(path)
    search = 'ST000.xls'
    for i in range(0,len(대상)):
        if search in 대상[i]:
            df = pd.read_excel(path+대상[i], encoding = 'euc-kr', sheet_name='조수별 공가요금 세부내역1')
        else :
            pass
    return df


def 경기북부데이터불러오기2(path) : 
    대상 = os.listdir(path)
    search = 'ST000.xls'
    for i in range(0,len(대상)):
        if search in 대상[i]:
            df = pd.read_excel(path+대상[i], encoding = 'euc-kr', sheet_name='조수별 공가요금 세부내역2')
        else :
            pass
    return df


def 경북데이터불러오기(path) : 
    대상 = os.listdir(path)
    search = 'SK계열'
    for i in range(0,len(대상)):
        if search in 대상[i]:
            df = pd.read_excel(path+대상[i], encoding = 'euc-kr')
        else :
            pass
    return df

def 부산데이터불러오기(path) : 
    대상 = os.listdir(path)
    search = '세부내역'
    for i in range(0,len(대상)):
        if search in 대상[i]:
            df = pd.read_excel(path+대상[i], encoding = 'euc-kr', sheet_name='가공세부내역')
        else :
            pass
    return df

def 충북데이터불러오기(path) : 
    대상 = os.listdir(path)
    search = '가공요금'
    for i in range(0,len(대상)):
        if search in 대상[i]:
            df = pd.read_excel(path+대상[i], encoding = 'euc-kr')
        else :
            pass
    return df

# splite 파일 불러오기
def open_sqlite(sqlite_file, sql_str):
    conn = sqlite3.connect(sqlite_file)
    ret = pd.read_sql(sql_str, conn)
    conn.close()
    return ret 

def save_sqlite(sqlite_file, table_name ,df):
    conn = sqlite3.connect(sqlite_file)
    df.to_sql(table_name, conn,if_exists='append')
    conn.close()

# 엑셀 데이터 불러오기

In [4]:
강원 = 강원데이터불러오기(강원path)

경기1 = 조수별데이터불러오기(경기path+'광명/')
경기2 = 조수별데이터불러오기(경기path+'광주/')
경기3 = 조수별데이터불러오기(경기path+'동용인/')
경기4 = 조수별데이터불러오기(경기path+'서수원/')
경기5 = 조수별데이터불러오기(경기path+'서용인/')
경기6 = 조수별데이터불러오기(경기path+'서평택/')
경기7 = 조수별데이터불러오기(경기path+'성남/')
경기8 = 조수별데이터불러오기(경기path+'안산/')
경기9 = 조수별데이터불러오기(경기path+'안성/')
경기10 = 조수별데이터불러오기(경기path+'안양/')
경기11 = 조수별데이터불러오기(경기path+'여주/')
경기12 = 조수별데이터불러오기(경기path+'오산/')
경기13 = 조수별데이터불러오기(경기path+'이천/')
경기14 = 조수별데이터불러오기(경기path+'직할/')
경기15 = 조수별데이터불러오기(경기path+'평택/')
경기16 = 조수별데이터불러오기(경기path+'하남/')
경기17 = 조수별데이터불러오기(경기path+'화성/')

경기북부1 = 경기북부데이터불러오기1(경기북부path)
경기북부2 = 경기북부데이터불러오기2(경기북부path)

경남 = 조수별데이터불러오기(경남path)

경북 = 경북데이터불러오기(경북path)

남서울 = pd.read_excel(남서울path+os.listdir(남서울path)[0], encoding = 'euc-kr', sheet_name='조수별공가요금세부내역')

부산 = 부산데이터불러오기(부산path)
# 부산 = pd.read_excel(부산path+os.listdir(부산path)[0], encoding = 'euc-kr', sheet_name='가공세부내역')

서울 = 조수별데이터불러오기(서울path)

인천 = pd.read_excel(인천path+os.listdir(인천path)[0], encoding = 'euc-kr', sheet_name='조수별')

전남강진 = 조수별데이터불러오기(전남path+'SKT/강진/')
전남고흥 = 조수별데이터불러오기(전남path+'SKT/고흥/')
전남곡성 = 조수별데이터불러오기(전남path+'SKT/곡성/')
전남광산 = 조수별데이터불러오기(전남path+'SKT/광산/')
전남광양 = 조수별데이터불러오기(전남path+'SKT/광양/')
전남구례 = 조수별데이터불러오기(전남path+'SKT/구례/')
전남나주 = 조수별데이터불러오기(전남path+'SKT/나주/')
전남담양 = 조수별데이터불러오기(전남path+'SKT/담양/')
전남목포 = 조수별데이터불러오기(전남path+'SKT/목포/')
전남무안 = 조수별데이터불러오기(전남path+'SKT/무안/')
전남보성 = 조수별데이터불러오기(전남path+'SKT/보성/')
전남서광주 = 조수별데이터불러오기(전남path+'SKT/서광주/')
전남순천 = 조수별데이터불러오기(전남path+'SKT/순천/')
전남신안 = 조수별데이터불러오기(전남path+'SKT/신안/')
전남여수 = 조수별데이터불러오기(전남path+'SKT/여수/')
전남영광 = 조수별데이터불러오기(전남path+'SKT/영광/')
전남영암 = 조수별데이터불러오기(전남path+'SKT/영암/')
전남완도 = 조수별데이터불러오기(전남path+'SKT/완도/')
전남장성 = 조수별데이터불러오기(전남path+'SKT/장성/')
전남장흥 = 조수별데이터불러오기(전남path+'SKT/장흥/')
전남직할 = 조수별데이터불러오기(전남path+'SKT/직할/')
전남진도 = 조수별데이터불러오기(전남path+'SKT/진도/')
전남함평 = 조수별데이터불러오기(전남path+'SKT/함평/')
전남해남 = 조수별데이터불러오기(전남path+'SKT/해남/')
전남화순 = 조수별데이터불러오기(전남path+'SKT/화순/')

전북1 = pd.read_excel(전북path+os.listdir(전북path)[0], encoding = 'euc-kr')
전북2 = pd.read_excel(전북path+os.listdir(전북path)[1], encoding = 'euc-kr')
전북3 = pd.read_excel(전북path+os.listdir(전북path)[2], encoding = 'euc-kr')
전북4 = pd.read_excel(전북path+os.listdir(전북path)[3], encoding = 'euc-kr')
전북5 = pd.read_excel(전북path+os.listdir(전북path)[4], encoding = 'euc-kr')
전북6 = pd.read_excel(전북path+os.listdir(전북path)[5], encoding = 'euc-kr')
전북7 = pd.read_excel(전북path+os.listdir(전북path)[6], encoding = 'euc-kr')
전북8 = pd.read_excel(전북path+os.listdir(전북path)[7], encoding = 'euc-kr')
전북9 = pd.read_excel(전북path+os.listdir(전북path)[8], encoding = 'euc-kr')
전북10 = pd.read_excel(전북path+os.listdir(전북path)[9], encoding = 'euc-kr')
전북11 = pd.read_excel(전북path+os.listdir(전북path)[10], encoding = 'euc-kr')
전북12 = pd.read_excel(전북path+os.listdir(전북path)[11], encoding = 'euc-kr')
전북13 = pd.read_excel(전북path+os.listdir(전북path)[12], encoding = 'euc-kr')
전북14 = pd.read_excel(전북path+os.listdir(전북path)[13], encoding = 'euc-kr')

전북1['지사명'] = os.listdir(전북path)[0].split("_")[3].split(".")[0]
전북2['지사명'] = os.listdir(전북path)[1].split("_")[3].split(".")[0]
전북3['지사명'] = os.listdir(전북path)[2].split("_")[3].split(".")[0]
전북4['지사명'] = os.listdir(전북path)[3].split("_")[3].split(".")[0]
전북5['지사명'] = os.listdir(전북path)[4].split("_")[3].split(".")[0]
전북6['지사명'] = os.listdir(전북path)[5].split("_")[3].split(".")[0]
전북7['지사명'] = os.listdir(전북path)[6].split("_")[3].split(".")[0]
전북8['지사명'] = os.listdir(전북path)[7].split("_")[3].split(".")[0]
전북9['지사명'] = os.listdir(전북path)[8].split("_")[3].split(".")[0]
전북10['지사명'] = os.listdir(전북path)[9].split("_")[3].split(".")[0]
전북11['지사명'] = os.listdir(전북path)[10].split("_")[3].split(".")[0]
전북12['지사명'] = os.listdir(전북path)[11].split("_")[3].split(".")[0]
전북13['지사명'] = os.listdir(전북path)[12].split("_")[3].split(".")[0]
전북14['지사명'] = os.listdir(전북path)[13].split("_")[3].split(".")[0]

제주1 = pd.read_excel(제주path+os.listdir(제주path)[0], encoding = 'euc-kr', sheet_name='직할')
제주2 = pd.read_excel(제주path+os.listdir(제주path)[0], encoding = 'euc-kr', sheet_name='서귀포')

충남1 = pd.read_excel(충남path+os.listdir(충남path)[0], encoding = 'euc-kr')
충남2 = pd.read_excel(충남path+os.listdir(충남path)[1], encoding = 'euc-kr')
충남3 = pd.read_excel(충남path+os.listdir(충남path)[2], encoding = 'euc-kr')
충남4 = pd.read_excel(충남path+os.listdir(충남path)[3], encoding = 'euc-kr')
충남5 = pd.read_excel(충남path+os.listdir(충남path)[4], encoding = 'euc-kr')
충남6 = pd.read_excel(충남path+os.listdir(충남path)[5], encoding = 'euc-kr')
충남7 = pd.read_excel(충남path+os.listdir(충남path)[6], encoding = 'euc-kr')
충남8 = pd.read_excel(충남path+os.listdir(충남path)[7], encoding = 'euc-kr')
충남9 = pd.read_excel(충남path+os.listdir(충남path)[8], encoding = 'euc-kr')
충남10 = pd.read_excel(충남path+os.listdir(충남path)[9], encoding = 'euc-kr')
충남11 = pd.read_excel(충남path+os.listdir(충남path)[10], encoding = 'euc-kr')
충남12 = pd.read_excel(충남path+os.listdir(충남path)[11], encoding = 'euc-kr')
충남13 = pd.read_excel(충남path+os.listdir(충남path)[12], encoding = 'euc-kr')
충남14 = pd.read_excel(충남path+os.listdir(충남path)[13], encoding = 'euc-kr')
충남15 = pd.read_excel(충남path+os.listdir(충남path)[14], encoding = 'euc-kr')
충남16 = pd.read_excel(충남path+os.listdir(충남path)[15], encoding = 'euc-kr')
충남17 = pd.read_excel(충남path+os.listdir(충남path)[16], encoding = 'euc-kr')
충남18 = pd.read_excel(충남path+os.listdir(충남path)[17], encoding = 'euc-kr')

충북 = 충북데이터불러오기(충북path)

# 데이터 가공하기

In [7]:
강원0 = 강원[['사업소코드', '전산화번호', '정상조수', '정상요금', '무단조수', '무단요금', '무단추징금(100%)', '신규위약조수',
       '신규위약금', '무단추징금(200%)', 'HFC조수', 'HFC요금', 'HFC추징금(100%)', '접속개소조수',
       '접속개소요금', '접속개소추징금(100%)', '자진신고무단조수', '자진신고무단요금', '자진신고무단추징금',
       '신규무단조수', '신규무단요금', '신규무단추징금(300%)']].reset_index()
강원0 = 강원0.drop(columns=['index'])
강원0['사업소코드'] = 강원0['사업소코드'].astype('object')

In [8]:
# 경기 지역
경기0 = pd.concat([경기1,경기2,경기3,경기4,경기5,경기6,경기7,경기8,경기9,경기10,경기11,경기12,경기13,경기14,경기15,경기16,경기17])
경기0 = 경기0[경기0['Unnamed: 1'].notnull()]
경기0 = 경기0[경기0['Unnamed: 10'].notnull()]
경기0 = 경기0[['Unnamed: 2', 'Unnamed: 1', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']].reset_index()
경기0 = 경기0.drop(columns=['index'])
경기0[['Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']]= 경기0[['Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']].astype('int64')

In [9]:
경기북부0 = pd.concat([경기북부1,경기북부2])
경기북부0 = 경기북부0[경기북부0['Unnamed: 1'].notnull()]
경기북부0 = 경기북부0[경기북부0['Unnamed: 10'].notnull()]
경기북부0 = 경기북부0[['Unnamed: 2', 'Unnamed: 1', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']].reset_index()
경기북부0 = 경기북부0.drop(columns=['index'])
경기북부0[['Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']]= 경기북부0[['Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']].astype('int64')

In [10]:
# 경남 지역 
경남0 = 경남[['사업소', '전산화번호', '정상조수', '정상요금', '무단조수', '무단요금', '무단추징금(100%)', '신규위약조수', '신규위약요금',
       '신규무단추징금(200%)', 'HFC조수', 'HFC요금', 'HFC추징금(100%)', '접속개소조수', '접속개소요금',
       '접속개소추징금(100%)', '자진신고무단조수', '자진신고무단요금', '자진신고무단추징금(150%)', '신규무단조수',
       '신규무단요금', '신규무단추징금(300%)']].reset_index()
경남0 = 경남0.drop(columns=['index'])
경남0['사업소'] = 경남0['사업소'].astype('object')

In [11]:
# 경북 지역
경북0 = 경북[['사업소코드', '전산화번호','정상조수', '정상요금', '무단조수', '무단요금', '무단추징금', '신규위약조수', '신규위약금', '신규위약무단추징금',
       'HFC조수', 'HFC요금', 'HFC추징금', '접속개소조수', '접속개소요금', '접속개소추징금', '자진신고무단조수',
       '자진신고무단요금', '자진신고무단추징금', '신규무단조수', '신규무단요금', '신규무단추징금']].reset_index()
경북0 = 경북0.drop(columns=['index'])
경북0 = 경북0[경북0['사업소코드'].notnull()]
경북0['사업소코드']=경북0['사업소코드'].astype('object')
경북0[['정상조수', '정상요금', '무단조수', '무단요금', '무단추징금', '신규위약조수',
       '신규위약금', '신규위약무단추징금', 'HFC조수', 'HFC요금', 'HFC추징금', '접속개소조수', '접속개소요금',
       '접속개소추징금', '자진신고무단조수', '자진신고무단요금', '자진신고무단추징금', '신규무단조수', '신규무단요금',
       '신규무단추징금']] = 경북0[['정상조수', '정상요금', '무단조수', '무단요금', '무단추징금', '신규위약조수',
       '신규위약금', '신규위약무단추징금', 'HFC조수', 'HFC요금', 'HFC추징금', '접속개소조수', '접속개소요금',
       '접속개소추징금', '자진신고무단조수', '자진신고무단요금', '자진신고무단추징금', '신규무단조수', '신규무단요금',
       '신규무단추징금']].astype('int64')

In [12]:
# 남서울 지역
남서울0 = 남서울[['사업소코드', '전산화번호','정상조수', '정상요금', '미승인 무단조수', '미승인 무단요금', '미승인 무단요금 추징금',
       '신규위약무단조수', '신규위약무단요금', '신규위약무단위약추징금', '정비제외-HFC조수', '정비제외-HFC요금',
       '정비제외-HFC추징금', '정비제외-접속개수조수', '정비제외-접속개소요금', '정비제외-접속개소추징금', '자진신고무단조수',
       '자진신고무단요금', '자진신고무단추징금', '신규무단조수', '신규무단요금', '신규무단추징금']].reset_index()
남서울0 = 남서울0.drop(columns=['index'])
남서울0['사업소코드'] = 남서울0['사업소코드'].astype('object')

In [13]:
부산.columns = ['지사명','순번','전산화번호','사업자코드','업체명','용도','적용단가','총조수','총금액',
             '정상조수', '정상요금', '무단조수', '무단요금', '무단추징금(100%)',
       '신규위약조수', '신규위약요금', '무단추징금(200%)', 'HFC무단조수', 'HFC무단요금',
       'HFC무단추징금(100%)', '접속개소조수', '접속개소요금', '접속개소추징금(100%)', '자진신고무단조수',
       '자진신고무단요금', '자진신고무단추징금(150%)', '신규무단조수', '신규무단요금', '신규무단추징금(300%)']
부산0 = 부산[7:]
부산0 = 부산0[['지사명','전산화번호', '정상조수', '정상요금', '무단조수', '무단요금', '무단추징금(100%)',
       '신규위약조수', '신규위약요금', '무단추징금(200%)', 'HFC무단조수', 'HFC무단요금',
       'HFC무단추징금(100%)', '접속개소조수', '접속개소요금', '접속개소추징금(100%)', '자진신고무단조수',
       '자진신고무단요금', '자진신고무단추징금(150%)', '신규무단조수', '신규무단요금', '신규무단추징금(300%)']].reset_index()
부산0 = 부산0.drop(columns=['index'])
부산0 = 부산0[부산0['정상조수'].notnull()]
부산0 [['정상조수', '정상요금', '무단조수', '무단요금', '무단추징금(100%)',
       '신규위약조수', '신규위약요금', '무단추징금(200%)', 'HFC무단조수', 'HFC무단요금',
       'HFC무단추징금(100%)', '접속개소조수', '접속개소요금', '접속개소추징금(100%)', '자진신고무단조수',
       '자진신고무단요금', '자진신고무단추징금(150%)', '신규무단조수', '신규무단요금', '신규무단추징금(300%)']] = 부산0 [['정상조수', '정상요금', '무단조수', '무단요금', '무단추징금(100%)',
       '신규위약조수', '신규위약요금', '무단추징금(200%)', 'HFC무단조수', 'HFC무단요금',
       'HFC무단추징금(100%)', '접속개소조수', '접속개소요금', '접속개소추징금(100%)', '자진신고무단조수',
       '자진신고무단요금', '자진신고무단추징금(150%)', '신규무단조수', '신규무단요금', '신규무단추징금(300%)']].astype('int64')

In [14]:
# 서울 지역
서울0 = 서울[서울['Unnamed: 1'].notnull()]
서울0 = 서울0[서울0['Unnamed: 11'].notnull()]

서울0 = 서울0[['Unnamed: 1', 'Unnamed: 3','Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29']].reset_index()
서울0 = 서울0.drop(columns=['index'])

서울0[['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29']]= 서울0[['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29']].astype('int64')

In [15]:
# 인천 지역 
인천0 = 인천[4:]
인천0 = 인천0[['Unnamed: 2', 'Unnamed: 1','Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']].reset_index()
인천0 = 인천0.drop(columns=['index'])
인천0[['Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']] = 인천0[['Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']].astype('int64')

In [16]:
# 전남 지역 
전남0 = pd.concat([전남강진,전남고흥,전남곡성,전남광산,전남광양,전남구례,전남나주,\
                전남담양,전남목포,전남무안,전남보성,전남서광주,전남순천,전남신안,\
                전남여수,전남영광,전남영암,전남완도,전남장성,전남장흥,전남직할,\
                전남진도,전남함평,전남해남,전남화순])
전남0 = 전남0[전남0['Unnamed: 1'].notnull()]
전남0 = 전남0[전남0['Unnamed: 10'].notnull()]
전남0 = 전남0[['Unnamed: 2', 'Unnamed: 1','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']].reset_index()
전남0 = 전남0.drop(columns=['index'])
전남0[['Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']] = 전남0[['Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']].astype('int64')

In [17]:
# 전북 지역
전북0 = pd.concat([전북1,전북2,전북3,전북4,전북5,전북6,전북7,전북8,전북9,전북10,전북11,전북12,전북13,전북14])
전북0 = 전북0[전북0['Unnamed: 1'].notnull()]
전북0 = 전북0[전북0['Unnamed: 10'].notnull()]

전북0 = 전북0[['지사명', 'Unnamed: 1','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']].reset_index()
전북0 = 전북0.drop(columns=['index'])
전북0[['Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']] = 전북0[['Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']].astype('int64')

In [18]:
# 제주 지역
제주 = pd.concat([제주1,제주2])
제주0 = 제주[제주['Unnamed: 1'].notnull()]
제주0 = 제주0[제주0['Unnamed: 12'].notnull()]

제주0 = 제주0[['Unnamed: 2', 'Unnamed: 1','Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']].reset_index()
제주0 = 제주0.drop(columns=['index'])
제주0[['Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']] = 제주0[['Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']].astype('int64')

In [19]:
# 충남 지역
충남0 = pd.concat([충남1,충남2,충남3,충남4,충남5,충남6,충남7,충남8,충남9,충남10,충남11,충남12,충남13,충남14,충남15,충남16,충남17,충남18])
충남0 = 충남0[충남0['Unnamed: 1'].notnull()]
충남0 = 충남0[충남0['Unnamed: 19'].notnull()]
충남0 = 충남0[['Unnamed: 2', 'Unnamed: 1','Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']].reset_index()
충남0 = 충남0.drop(columns=['index'])
충남0[['Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28']] = 충남0[['Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28']].astype('int64')

In [20]:
# 충북 지역 : 데이터의 컬럼명이 문제 없는지 확인 필요함
충북0 = 충북
충북0 = 충북0[['사업소코드', '전산화번호', '정상조수', '정상요금', '무단조수', '무단요금', '무단추징금(100%)', '신규위약조수',
       '신규위약금', '무단추징금(200%)', 'HFC조수', 'HFC요금', 'HFC추징금(100%)', '접속개소조수',
       '접속개소요금', '접속개소추징금(100%)', '자진신고무단조수', '자진신고무단요금', '자진신고무단추징금',
       '신규무단조수', '신규무단요금', '신규무단추징금(300%)']].reset_index()
충북0 = 충북0.drop(columns=['index'])
충북0[['정상조수', '정상요금', '무단조수', '무단요금', '무단추징금(100%)', '신규위약조수',
       '신규위약금', '무단추징금(200%)', 'HFC조수', 'HFC요금', 'HFC추징금(100%)', '접속개소조수',
       '접속개소요금', '접속개소추징금(100%)', '자진신고무단조수', '자진신고무단요금', '자진신고무단추징금',
       '신규무단조수', '신규무단요금', '신규무단추징금(300%)']] = 충북0[['정상조수', '정상요금', '무단조수', '무단요금', '무단추징금(100%)', '신규위약조수',
       '신규위약금', '무단추징금(200%)', 'HFC조수', 'HFC요금', 'HFC추징금(100%)', '접속개소조수',
       '접속개소요금', '접속개소추징금(100%)', '자진신고무단조수', '자진신고무단요금', '자진신고무단추징금',
       '신규무단조수', '신규무단요금', '신규무단추징금(300%)']].astype('int64')

# 컬럼명 변경하기

In [21]:
강원0.rename(columns={'사업소코드':'사업소코드','전산화번호':'전산화번호','정상조수':'정상조수','정상요금':'정상요금','무단조수':'무단조수','무단요금':'무단요금','무단추징금(100%)':'무단추징금(100%)','신규위약조수':'신규위약조수','신규위약금':'신규위약요금','무단추징금(200%)':'무단추징금(200%)','HFC조수':'HFC무단조수','HFC요금':'HFC무단요금','HFC추징금(100%)':'HFC무단추징금(100%)','접속개소조수':'접속개소조수','접속개소요금':'접속개소요금','접속개소추징금(100%)':'접속개소추징금(100%)','자진신고무단조수':'자진신고무단조수','자진신고무단요금':'자진신고무단요금','자진신고무단추징금':'자진신고무단추징금(150%)','신규무단조수':'신규무단조수','신규무단요금':'신규무단요금','신규무단추징금(300%)':'신규무단추징금(300%)',},inplace = True)
경기0.rename(columns={'Unnamed: 2':'사업소코드','Unnamed: 1':'전산화번호','Unnamed: 9':'정상조수','Unnamed: 10':'정상요금','Unnamed: 11':'무단조수','Unnamed: 12':'무단요금','Unnamed: 13':'무단추징금(100%)','Unnamed: 14':'신규위약조수','Unnamed: 15':'신규위약요금','Unnamed: 16':'무단추징금(200%)','Unnamed: 17':'HFC무단조수','Unnamed: 18':'HFC무단요금','Unnamed: 19':'HFC무단추징금(100%)','Unnamed: 20':'접속개소조수','Unnamed: 21':'접속개소요금','Unnamed: 22':'접속개소추징금(100%)','Unnamed: 23':'자진신고무단조수','Unnamed: 24':'자진신고무단요금','Unnamed: 25':'자진신고무단추징금(150%)','Unnamed: 26':'신규무단조수','Unnamed: 27':'신규무단요금','Unnamed: 28':'신규무단추징금(300%)',},inplace = True)

In [22]:
경기북부0.rename(columns={'Unnamed: 2':'사업소코드','Unnamed: 1':'전산화번호','Unnamed: 9':'정상조수','Unnamed: 10':'정상요금','Unnamed: 11':'무단조수','Unnamed: 12':'무단요금','Unnamed: 13':'무단추징금(100%)','Unnamed: 14':'신규위약조수','Unnamed: 15':'신규위약요금','Unnamed: 16':'무단추징금(200%)','Unnamed: 17':'HFC무단조수','Unnamed: 18':'HFC무단요금','Unnamed: 19':'HFC무단추징금(100%)','Unnamed: 20':'접속개소조수','Unnamed: 21':'접속개소요금','Unnamed: 22':'접속개소추징금(100%)','Unnamed: 23':'자진신고무단조수','Unnamed: 24':'자진신고무단요금','Unnamed: 25':'자진신고무단추징금(150%)','Unnamed: 26':'신규무단조수','Unnamed: 27':'신규무단요금','Unnamed: 28':'신규무단추징금(300%)',},inplace = True)
경남0.rename(columns={'사업소':'사업소코드','전산화번호':'전산화번호','정상조수':'정상조수','정상요금':'정상요금','무단조수':'무단조수','무단요금':'무단요금','무단추징금(100%)':'무단추징금(100%)','신규위약조수':'신규위약조수','신규위약요금':'신규위약요금','신규무단추징금(200%)':'무단추징금(200%)','HFC조수':'HFC무단조수','HFC요금':'HFC무단요금','HFC추징금(100%)':'HFC무단추징금(100%)','접속개소조수':'접속개소조수','접속개소요금':'접속개소요금','접속개소추징금(100%)':'접속개소추징금(100%)','자진신고무단조수':'자진신고무단조수','자진신고무단요금':'자진신고무단요금','자진신고무단추징금(150%)':'자진신고무단추징금(150%)','신규무단조수':'신규무단조수','신규무단요금':'신규무단요금','신규무단추징금(300%)':'신규무단추징금(300%)',},inplace = True)
경북0.rename(columns={'사업소코드':'사업소코드','전산화번호':'전산화번호','정상조수':'정상조수','정상요금':'정상요금','무단조수':'무단조수','무단요금':'무단요금','무단추징금':'무단추징금(100%)','신규위약조수':'신규위약조수','신규위약금':'신규위약요금','신규위약무단추징금':'무단추징금(200%)','HFC조수':'HFC무단조수','HFC요금':'HFC무단요금','HFC추징금':'HFC무단추징금(100%)','접속개소조수':'접속개소조수','접속개소요금':'접속개소요금','접속개소추징금':'접속개소추징금(100%)','자진신고무단조수':'자진신고무단조수','자진신고무단요금':'자진신고무단요금','자진신고무단추징금':'자진신고무단추징금(150%)','신규무단조수':'신규무단조수','신규무단요금':'신규무단요금','신규무단추징금':'신규무단추징금(300%)',},inplace = True)
남서울0.rename(columns={'사업소코드':'사업소코드','전산화번호':'전산화번호','정상조수':'정상조수','정상요금':'정상요금','미승인 무단조수':'무단조수','미승인 무단요금':'무단요금','미승인 무단요금 추징금':'무단추징금(100%)','신규위약무단조수':'신규위약조수','신규위약무단요금':'신규위약요금','신규위약무단위약추징금':'무단추징금(200%)','정비제외-HFC조수':'HFC무단조수','정비제외-HFC요금':'HFC무단요금','정비제외-HFC추징금':'HFC무단추징금(100%)','정비제외-접속개수조수':'접속개소조수','정비제외-접속개소요금':'접속개소요금','정비제외-접속개소추징금':'접속개소추징금(100%)','자진신고무단조수':'자진신고무단조수','자진신고무단요금':'자진신고무단요금','자진신고무단추징금':'자진신고무단추징금(150%)','신규무단조수':'신규무단조수','신규무단요금':'신규무단요금','신규무단추징금':'신규무단추징금(300%)',},inplace = True)
서울0.rename(columns={'Unnamed: 1':'사업소코드','Unnamed: 3':'전산화번호','Unnamed: 10':'정상조수','Unnamed: 11':'정상요금','Unnamed: 12':'무단조수','Unnamed: 13':'무단요금','Unnamed: 14':'무단추징금(100%)','Unnamed: 15':'신규위약조수','Unnamed: 16':'신규위약요금','Unnamed: 17':'무단추징금(200%)','Unnamed: 18':'HFC무단조수','Unnamed: 19':'HFC무단요금','Unnamed: 20':'HFC무단추징금(100%)','Unnamed: 21':'접속개소조수','Unnamed: 22':'접속개소요금','Unnamed: 23':'접속개소추징금(100%)','Unnamed: 24':'자진신고무단조수','Unnamed: 25':'자진신고무단요금','Unnamed: 26':'자진신고무단추징금(150%)','Unnamed: 27':'신규무단조수','Unnamed: 28':'신규무단요금','Unnamed: 29':'신규무단추징금(300%)',},inplace = True)
전남0.rename(columns={'Unnamed: 2':'사업소코드','Unnamed: 1':'전산화번호','Unnamed: 9':'정상조수','Unnamed: 10':'정상요금','Unnamed: 11':'무단조수','Unnamed: 12':'무단요금','Unnamed: 13':'무단추징금(100%)','Unnamed: 14':'신규위약조수','Unnamed: 15':'신규위약요금','Unnamed: 16':'무단추징금(200%)','Unnamed: 17':'HFC무단조수','Unnamed: 18':'HFC무단요금','Unnamed: 19':'HFC무단추징금(100%)','Unnamed: 20':'접속개소조수','Unnamed: 21':'접속개소요금','Unnamed: 22':'접속개소추징금(100%)','Unnamed: 23':'자진신고무단조수','Unnamed: 24':'자진신고무단요금','Unnamed: 25':'자진신고무단추징금(150%)','Unnamed: 26':'신규무단조수','Unnamed: 27':'신규무단요금','Unnamed: 28':'신규무단추징금(300%)',},inplace = True)
제주0.rename(columns={'Unnamed: 2':'사업소코드','Unnamed: 1':'전산화번호','Unnamed: 9':'정상조수','Unnamed: 10':'정상요금','Unnamed: 11':'무단조수','Unnamed: 12':'무단요금','Unnamed: 13':'무단추징금(100%)','Unnamed: 14':'신규위약조수','Unnamed: 15':'신규위약요금','Unnamed: 16':'무단추징금(200%)','Unnamed: 17':'HFC무단조수','Unnamed: 18':'HFC무단요금','Unnamed: 19':'HFC무단추징금(100%)','Unnamed: 20':'접속개소조수','Unnamed: 21':'접속개소요금','Unnamed: 22':'접속개소추징금(100%)','Unnamed: 23':'자진신고무단조수','Unnamed: 24':'자진신고무단요금','Unnamed: 25':'자진신고무단추징금(150%)','Unnamed: 26':'신규무단조수','Unnamed: 27':'신규무단요금','Unnamed: 28':'신규무단추징금(300%)',},inplace = True)
충남0.rename(columns={'Unnamed: 2':'사업소코드','Unnamed: 1':'전산화번호','Unnamed: 9':'정상조수','Unnamed: 10':'정상요금','Unnamed: 11':'무단조수','Unnamed: 12':'무단요금','Unnamed: 13':'무단추징금(100%)','Unnamed: 14':'신규위약조수','Unnamed: 15':'신규위약요금','Unnamed: 16':'무단추징금(200%)','Unnamed: 17':'HFC무단조수','Unnamed: 18':'HFC무단요금','Unnamed: 19':'HFC무단추징금(100%)','Unnamed: 20':'접속개소조수','Unnamed: 21':'접속개소요금','Unnamed: 22':'접속개소추징금(100%)','Unnamed: 23':'자진신고무단조수','Unnamed: 24':'자진신고무단요금','Unnamed: 25':'자진신고무단추징금(150%)','Unnamed: 26':'신규무단조수','Unnamed: 27':'신규무단요금','Unnamed: 28':'신규무단추징금(300%)',},inplace = True)
충북0.rename(columns={'사업소코드':'사업소코드','전산화번호':'전산화번호','정상조수':'정상조수','정상요금':'정상요금','무단조수':'무단조수','무단요금':'무단요금','무단추징금(100%)':'무단추징금(100%)','신규위약조수':'신규위약조수','신규위약금':'신규위약요금','무단추징금(200%)':'무단추징금(200%)','HFC조수':'HFC무단조수','HFC요금':'HFC무단요금','HFC추징금(100%)':'HFC무단추징금(100%)','접속개소조수':'접속개소조수','접속개소요금':'접속개소요금','접속개소추징금(100%)':'접속개소추징금(100%)','자진신고무단조수':'자진신고무단조수','자진신고무단요금':'자진신고무단요금','자진신고무단추징금':'자진신고무단추징금(150%)','신규무단조수':'신규무단조수','신규무단요금':'신규무단요금','신규무단추징금(300%)':'신규무단추징금(300%)',},inplace = True)
인천0.rename(columns={'Unnamed: 2':'지사명','Unnamed: 1':'전산화번호','Unnamed: 9':'정상조수','Unnamed: 10':'정상요금','Unnamed: 11':'무단조수','Unnamed: 12':'무단요금','Unnamed: 13':'무단추징금(100%)','Unnamed: 14':'신규위약조수','Unnamed: 15':'신규위약요금','Unnamed: 16':'무단추징금(200%)','Unnamed: 17':'HFC무단조수','Unnamed: 18':'HFC무단요금','Unnamed: 19':'HFC무단추징금(100%)','Unnamed: 20':'접속개소조수','Unnamed: 21':'접속개소요금','Unnamed: 22':'접속개소추징금(100%)','Unnamed: 23':'자진신고무단조수','Unnamed: 24':'자진신고무단요금','Unnamed: 25':'자진신고무단추징금(150%)','Unnamed: 26':'신규무단조수','Unnamed: 27':'신규무단요금','Unnamed: 28':'신규무단추징금(300%)',},inplace = True)
전북0.rename(columns={'지사명':'지사명','Unnamed: 1':'전산화번호','Unnamed: 9':'정상조수','Unnamed: 10':'정상요금','Unnamed: 11':'무단조수','Unnamed: 12':'무단요금','Unnamed: 13':'무단추징금(100%)','Unnamed: 14':'신규위약조수','Unnamed: 15':'신규위약요금','Unnamed: 16':'무단추징금(200%)','Unnamed: 17':'HFC무단조수','Unnamed: 18':'HFC무단요금','Unnamed: 19':'HFC무단추징금(100%)','Unnamed: 20':'접속개소조수','Unnamed: 21':'접속개소요금','Unnamed: 22':'접속개소추징금(100%)','Unnamed: 23':'자진신고무단조수','Unnamed: 24':'자진신고무단요금','Unnamed: 25':'자진신고무단추징금(150%)','Unnamed: 26':'신규무단조수','Unnamed: 27':'신규무단요금','Unnamed: 28':'신규무단추징금(300%)',},inplace = True)
### 부산은 상단에 이미 변경이 완료됨

In [23]:
강원0['사업소코드'] = 강원0['사업소코드'].astype('int64')
경기0['사업소코드']=경기0['사업소코드'].astype('int64')
경기북부0['사업소코드']=경기북부0['사업소코드'].astype('int64')
경남0['사업소코드']=경남0['사업소코드'].astype('int64')
경북0['사업소코드']=경북0['사업소코드'].astype('int64')
남서울0['사업소코드']=남서울0['사업소코드'].astype('int64')
서울0['사업소코드']=서울0['사업소코드'].astype('int64')
전남0['사업소코드']=전남0['사업소코드'].astype('int64')
제주0['사업소코드']=제주0['사업소코드'].astype('int64')
충남0['사업소코드']=충남0['사업소코드'].astype('int64')
충북0['사업소코드']=충북0['사업소코드'].astype('int64')

# 사업소코드 테이블과 매칭하기

In [24]:
# splite 파일 불러오기
def open_sqlite(sqlite_file, sql_str):
    conn = sqlite3.connect(sqlite_file)
    ret = pd.read_sql(sql_str, conn)
    conn.close()
    return ret 


sqlite = 'd:/dev/SQL_DB/한전조수DB.db'
sql_str = 'SELECT * FROM 사업소코드'

사업소코드 = open_sqlite(sqlite, sql_str)
사업소코드 = 사업소코드.drop(columns=['index'])

In [25]:
전북f = pd.merge(전북0,사업소코드, on='지사명', how='left')
인천f = pd.merge(인천0,사업소코드, on='지사명', how='left')
부산f = pd.merge(부산0,사업소코드, on='지사명', how='left')
강원f = pd.merge(강원0,사업소코드, on= '사업소코드', how  = 'left')
경기f = pd.merge(경기0,사업소코드, on ='사업소코드', how = 'left')
경기북부f = pd.merge(경기북부0,사업소코드, on ='사업소코드', how = 'left')
경남f = pd.merge(경남0,사업소코드, on ='사업소코드', how = 'left')
경북f = pd.merge(경북0,사업소코드, on ='사업소코드', how = 'left')
남서울f = pd.merge(남서울0,사업소코드, on ='사업소코드', how = 'left')
서울f = pd.merge(서울0,사업소코드, on ='사업소코드', how = 'left')
전남f = pd.merge(전남0,사업소코드, on ='사업소코드', how = 'left')
제주f = pd.merge(제주0,사업소코드, on ='사업소코드', how = 'left')
충남f = pd.merge(충남0,사업소코드, on ='사업소코드', how = 'left')
충북f = pd.merge(충북0,사업소코드, on ='사업소코드', how = 'left')

# 테이블별 년월 입력하기 
* 초기 설정한 month값으로 입력되어진다

In [26]:
전북f['month'] = month
인천f['month'] = month
부산f['month'] = month
강원f['month'] = month
경기f['month'] = month
경기북부f['month'] = month
경남f['month'] = month
경북f['month'] = month
남서울f['month'] = month
서울f['month'] = month
전남f['month'] = month
제주f['month'] = month
충남f['month'] = month
충북f['month'] = month

# SQLite DB 입력하기

In [29]:
save_sqlite(sqlite, '가공요금표', 강원f)
save_sqlite(sqlite, '가공요금표', 경기f)
save_sqlite(sqlite, '가공요금표', 경기북부f)
save_sqlite(sqlite, '가공요금표', 경남f)
save_sqlite(sqlite, '가공요금표', 경북f)
save_sqlite(sqlite, '가공요금표', 남서울f)
save_sqlite(sqlite, '가공요금표', 부산f)
save_sqlite(sqlite, '가공요금표', 서울f)
save_sqlite(sqlite, '가공요금표', 인천f)
save_sqlite(sqlite, '가공요금표', 전남f)
save_sqlite(sqlite, '가공요금표', 전북f)
save_sqlite(sqlite, '가공요금표', 제주f)
save_sqlite(sqlite, '가공요금표', 충남f)
save_sqlite(sqlite, '가공요금표', 충북f)